# Generated by Django 2.2.16 on 2022-05-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_title_rating'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('review', 'author'), name='unique_comment'),
        ),
    ]
